In [6]:
FILE_PATH = "/content/hostel_bois.txt"

In [37]:
file = open(FILE_PATH, "r")
line = file.readline()
print(line)
file.close()

01/04/24, 01:12 - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.



In [17]:
first = messages[1]
parts = first.split(" - ", 1)
print(parts[0])
print(parts[1])

01/04/24, 01:13
Priya created group "Hostel Bois 4ever"



In [41]:
#Whatsapp chat parser
chat = []
for line in lines:
    if " - " in line and ": " in line:
        parts = line.split(" - ", 1)
        date_time = parts[0]
        sender_text = parts[1]
        sender, text = sender_text.split(": ", 1)
        chat.append([date_time, sender, text.strip()])
print("Total messages:", len(chat))
print("First message:", chat[0])

Total messages: 3174
First message: ['01/04/24, 01:17', 'Rahul', 'scene fix']


In [43]:
#Group Overview
people = []
message_counts = {}
for message in chat:
    sender = message[1]
    if sender not in people:
        people.append(sender)
        message_counts[sender] = 0
    message_counts[sender] += 1
print("Total messages:", len(chat))
print("Total participants:", len(people))
for person in people:
    print(person, ":", message_counts[person])

Total messages: 3174
Total participants: 6
Rahul : 953
Priya : 718
Karan : 354
Neha : 635
Aman : 490
Vikas : 24


In [44]:
#Most Active Day and Hour
day_count = {}
hour_count = {}
for message in chat:
    date_time = message[0]
    date = date_time.split(",")[0]
    time = date_time.split(",")[1].strip()
    hour = int(time.split(":")[0])
    if date not in day_count:
        day_count[date] = 0
    day_count[date] += 1
    if hour not in hour_count:
        hour_count[hour] = 0
    hour_count[hour] += 1
active_day = max(day_count, key=day_count.get)
active_hour = max(hour_count, key=hour_count.get)
print("Most active day:", active_day)
print("Messages on that day:", day_count[active_day])
print("Most active hour:", active_hour)
print("Messages in that hour:", hour_count[active_hour])

Most active day: 04/05/24
Messages on that day: 76
Most active hour: 18
Messages in that hour: 248


In [46]:
#NumPy Activity Heatmap
from datetime import datetime
import numpy as np
activity = np.zeros((7, 24), dtype=int)
for message in chat:
    date_time = message[0]
    date = date_time.split(",")[0]
    time = date_time.split(",")[1].strip()
    day = datetime.strptime(date, "%d/%m/%y").weekday()
    hour = int(time.split(":")[0])
    activity[day][hour] += 1
print("Activity Heatmap")
print(activity)

Activity Heatmap
[[ 8 17 13 11 11  0  4 10 18 12 18 15 31 30 18 20 30 23 49 35 30 32 19 28]
 [11 16 13 25 14 12  4  9 18 21 19  7 21 18 20  8 27 26 40 16 21 29 15 16]
 [ 6 11 12  6 11  4  0  8 20 31 25 15 27 17 37 27 38 25 21 34 26 46 19 17]
 [ 7  5 15 14  9  6  1  9 16 23 20 30 37 24 26 18 33 19 36 35 32 18 20 22]
 [ 5 11 17  4 22  3  6  4 21 26 23 11 23 25 18 22 17 17 41 25 15 18 12 17]
 [11 15  9 10 17  0  3  7 14 21 23 14 20 22 25  9 25 40 34 43 20 17 15 45]
 [ 9  7  4  7 26  4 15  8 15 17 32 22 34 23 18 27 19 23 27 40 22 17 16 14]]


In [47]:
#Top Words
word_count = {}
for message in chat:
    words = message[2].lower().split()
    for word in words:
        word = word.strip(".,!?\"'()[]{}:")
        if len(word) > 2:
            if word not in word_count:
                word_count[word] = 0
            word_count[word] += 1
top_words = sorted(word_count, key=word_count.get, reverse=True)
print("Top 20 words:")
for word in top_words[:20]:
    print(word, ":", word_count[word])

Top 20 words:
the : 1494
and : 1013
was : 400
this : 326
how : 321
guys : 318
you : 312
about : 274
for : 270
hai : 268
today : 257
his : 217
that : 211
have : 209
just : 208
which : 202
everyone : 187
telling : 179
from : 174
bhai : 160


In [48]:
#Response Speed & Silent Streaks
from datetime import datetime
response_times = []
silent_streaks = []
previous_time = None
for message in chat:
    current_time = datetime.strptime(message[0], "%d/%m/%y, %H:%M")

    if previous_time is not None:
        difference = (current_time - previous_time).total_seconds() / 60

        if difference <= 60:
            response_times.append(difference)
        else:
            silent_streaks.append(difference)
    previous_time = current_time
if len(response_times) > 0:
    average_response = sum(response_times) / len(response_times)
else:
    average_response = 0
if len(silent_streaks) > 0:
    longest_silence = max(silent_streaks)
else:
    longest_silence = 0
print("Average response time:", round(average_response, 2), "minutes")
print("Longest silent streak:", round(longest_silence / 60, 2), "hours")

Average response time: 13.12 minutes
Longest silent streak: 5.98 hours


In [49]:
#Personality Archetypes
archetypes = {
    "Rahul": "THE SPAMMER",
    "Priya": "THE GROUP MOM",
    "Aman": "THE NIGHT OWL",
    "Karan": "THE STORYTELLER",
    "Neha": "THE DRAMA QUEEN",
    "Vikas": "THE GHOST"
}

print("GROUPDNA PERSONALITY ARCHETYPES")

for person in people:
    if person in archetypes:
        print(person, "->", archetypes[person])

GROUPDNA PERSONALITY ARCHETYPES
Rahul -> THE SPAMMER
Priya -> THE GROUP MOM
Karan -> THE STORYTELLER
Neha -> THE DRAMA QUEEN
Aman -> THE NIGHT OWL
Vikas -> THE GHOST


In [50]:
#Final GroupDNA Report
print("=" * 40)
print("       GROUPDNA FINAL REPORT")
print("=" * 40)

print("\nGROUP OVERVIEW")
print("Total messages:", len(chat))
print("Participants:", len(people))

for person in people:
    print(person, "-", message_counts[person], "messages")

print("\nMOST ACTIVE")
print("Day:", active_day)
print("Hour:", active_hour)

print("\nTOP WORDS")
for word in top_words[:10]:
    print(word, "-", word_count[word])

print("\nRESPONSE & SILENCE")
print("Average response:", round(average_response, 2), "minutes")
print("Longest silence:", round(longest_silence / 60, 2), "hours")

print("\nPERSONALITY ARCHETYPES")
for person in people:
    if person in archetypes:
        print(person, "->", archetypes[person])

print("\nGROUPDNA analysis completed successfully!")

       GROUPDNA FINAL REPORT

GROUP OVERVIEW
Total messages: 3174
Participants: 6
Rahul - 953 messages
Priya - 718 messages
Karan - 354 messages
Neha - 635 messages
Aman - 490 messages
Vikas - 24 messages

MOST ACTIVE
Day: 04/05/24
Hour: 18

TOP WORDS
the - 1494
and - 1013
was - 400
this - 326
how - 321
guys - 318
you - 312
about - 274
for - 270
hai - 268

RESPONSE & SILENCE
Average response: 13.12 minutes
Longest silence: 5.98 hours

PERSONALITY ARCHETYPES
Rahul -> THE SPAMMER
Priya -> THE GROUP MOM
Karan -> THE STORYTELLER
Neha -> THE DRAMA QUEEN
Aman -> THE NIGHT OWL
Vikas -> THE GHOST

GROUPDNA analysis completed successfully!
